-- AlterTable
ALTER TABLE "MyUser" ADD COLUMN     "lat" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "lng" DOUBLE PRECISION DEFAULT 0.0;

-- AlterTable
ALTER TABLE "MyVendor" ADD COLUMN     "lat" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "lng" DOUBLE PRECISION DEFAULT 0.0;

-- AlterTable
ALTER TABLE "MyWorker" ADD COLUMN     "lat" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "lng" DOUBLE PRECISION DEFAULT 0.0;
