-- AlterTable
ALTER TABLE "MyUser" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "mobileNumber" DROP NOT NULL;

-- AlterTable
ALTER TABLE "MyVendor" ALTER COLUMN "ownerName" DROP NOT NULL,
ALTER COLUMN "age" DROP NOT NULL;

-- AlterTable
ALTER TABLE "MyWorker" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "mobileNumber" DROP NOT NULL,
ALTER COLUMN "age" DROP NOT NULL;
